config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, skip: [
    :sessions,
    :registrations,
    :passwords
  ]

  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    match 'logout' => 'devise/sessions#destroy', as: :destroy_user_session, via: [:get, :delete]

    get 'account-recovery' => 'devise/passwords#new', as: :new_user_password
    post 'account-recovery' => 'devise/passwords#create', as: :user_password
    get 'reset-password' => 'devise/passwords#edit', as: :reset_user_password
    patch 'reset-password' => 'devise/passwords#update', as: :confirm_user_password


    get 'signup' => 'devise/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/registrations#create', as: :user_registration
    get 'change-password' => 'devise/registrations#edit', as: :edit_user_registration
    patch 'change-password' => 'devise/registrations#update', as: :update_user_registration
    delete 'delete-account' => 'devise/registrations#destroy', as: :destroy_user_registration
  end

  resources :categories
  resources :expenses
  resources :smart_expenses

  authenticated do
    root to: 'pages#home'
  end

  root to: 'pages#landing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  validates :name, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :amount, :description, :category_ids, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/smart_expense.rb
class SmartExpense < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :expression, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories
  has_many :expenses
  has_many :smart_expenses

  attribute :currency, :string, default: '€'

  validates :currency, presence: true

  def current_month_expenses
    expenses.where('created_at >= ?', DateTime.now.beginning_of_month)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  # GET /categories
  def index
    @categories = current_user.categories
  end

  # GET /categories/1
  def show
    @category = current_user.categories.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = current_user.categories.find(params[:id])
  end

  # POST /categories
  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    @category = current_user.categories.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_url, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit(:user_id, :name)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  # GET /expenses
  def index
    @expenses = current_user.expenses.order(created_at: :desc)
  end

  # GET /expenses/1
  def show
    @expense = current_user.expenses.find(params[:id])
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @smart_expenses = current_user.smart_expenses
  end

  # GET /expenses/1/edit
  def edit
    @expense = current_user.expenses.find(params[:id])
  end

  # POST /expenses
  def create
    @expense = current_user.expenses.new(expense_params)

    if @expense.save
      redirect_to expenses_url, notice: 'Expense was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /expenses/1
  def update
    @expense = current_user.expenses.find(params[:id])
    if @expense.update(expense_params)
      redirect_to @expense, notice: 'Expense was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /expenses/1
  def destroy
    @expense = current_user.expenses.find(params[:id])
    @expense.destroy
    redirect_to expenses_url, notice: 'Expense was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def expense_params
    params.require(:expense).permit(:user_id, :amount, :created_at, :description, category_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @expenses = current_user.current_month_expenses.order(created_at: :desc)
    @sum_expenses_current_month = @expenses.sum(:amount)
  end
end

app/controllers/smart_expenses_controller.rb
class SmartExpensesController < ApplicationController
  before_action :authenticate_user!

  # GET /smart_expenses
  def index
    @smart_expenses = current_user.smart_expenses
  end

  # GET /smart_expenses/1
  def show
    @smart_expense = current_user.smart_expenses.find(params[:id])
  end

  # GET /smart_expenses/new
  def new
    @smart_expense = SmartExpense.new
  end

  # GET /smart_expenses/1/edit
  def edit
    @smart_expense = current_user.smart_expenses.find(params[:id])
  end

  # POST /smart_expenses
  def create
    @smart_expense = current_user.smart_expenses.new(smart_expense_params)

    if @smart_expense.save
      redirect_to smart_expenses_url, notice: 'Smart expense was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /smart_expenses/1
  def update
    @smart_expense = current_user.smart_expenses.find(params[:id])
    if @smart_expense.update(smart_expense_params)
      redirect_to @smart_expense, notice: 'Smart expense was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /smart_expenses/1
  def destroy
    @smart_expense = current_user.smart_expenses.find(params[:id])
    @smart_expense.destroy
    redirect_to smart_expenses_url, notice: 'Smart expense was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def smart_expense_params
    params.require(:smart_expense).permit(:user_id, :amount, :description, :expression, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true, builder: InlineErrorsFormBuilder, class: 'form') do |form| %>
  <div class='form__field'>
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name, class: 'input', required: true %>
    <%= form.inline_errors :name %>
  </div>

  <div class='form__actions'>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class='actionable-table'>
  <thead>
    <tr>
      <th>Name</th>
      <th class='actionable-table-actions'></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td class='actionable-table-actions'>
          <%= link_to '👀', category, class: 'emoji-link' %>
          <%= link_to '✏️', edit_category_path(category), class: 'emoji-link' %>
          <%= link_to '💣', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'emoji-link' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/expenses/_expenses_table.html.erb
<table class='actionable-table'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Description</th>
      <th class='actionable-table-actions'></th>
    </tr>
  </thead>

  <tbody>
    <% expenses.each do |expense| %>
      <tr>
        <td><%= l expense.created_at, format: :short %></td>
        <td><%= number_to_currency(expense.amount, unit: current_user.currency) %></td>
        <td><%= expense.description %></td>
        <td class='actionable-table-actions'>
          <%= link_to '👀', expense, class: 'emoji-link' %>
          <%= link_to '✏️', edit_expense_path(expense), class: 'emoji-link' %>
          <%= link_to '💣', expense, method: :delete, data: { confirm: 'Are you sure?' }, class: 'emoji-link' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true, builder: InlineErrorsFormBuilder, class: 'form') do |form| %>
  <div class='form__field form__field--currency'>
    <%= form.label :amount %>
    <span>
      <%= form.number_field :amount, min: 0, step: 'any', id: :expense_amount, class: 'input', required: true %>
      <%= current_user.currency %>
    </span>
    <%= form.inline_errors :amount %>
  </div>

  <div class='form__field'>
    <%= form.label :description %>
    <%= form.text_area :description, id: :expense_description, class: 'h-fixed-textarea', required: true %>
    <%= form.inline_errors :description %>
  </div>

  <div class='form__field'>
    <%= form.label :categories %>
    <%= form.collection_select :category_ids, current_user.categories, :id, :name, {},
      {
        multiple: true,
        id: :expense_categories,
        class: 'h-fixed-select',
        required: true
      }
    %>
    <%= form.inline_errors_categories %>
  </div>

  <div class='form__field form__field--date'>
    <%= form.label :date %>
    <%= form.date_select :created_at, id: :expense_date %>
  </div>

  <div class='form__actions'>
    <%= form.submit %>
  </div>
<% end %>

<%= javascript_tag do %>
  window.smart_expenses = <%= @smart_expenses.to_json.html_safe %>;
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Expenses</h1>

<h2>This month: <%= number_to_currency(@sum_expenses_current_month, unit: current_user.currency) %></h2>

<%= render 'expenses_table', expenses: @expenses %>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@expense.amount, unit: current_user.currency) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @expense.categories.pluck(:name).join(', ') %>
</p>

<p>
  <strong>Date:</strong>
  <%= l @expense.created_at, format: :short %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class='container'>
      <div class='alerts'>
        <% flash.each do |key, value| %>
          <div class='alert alert-<%= key %>'><%= value %></div>
        <% end %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Month expenses</h1>

<h2>Total Amount: <%= number_to_currency(@sum_expenses_current_month, unit: current_user.currency) %></h2>

<%= render 'expenses/expenses_table', expenses: @expenses %>

<br>

<%= link_to 'Expenses', expenses_path %>

<%= link_to 'Smart Expenses', smart_expenses_path %>

<%= link_to 'Categories', categories_path %>

app/views/pages/landing.html.erb
<h1>Pages#landing</h1>
<p>Find me in app/views/pages/landing.html.erb</p>

app/views/smart_expenses/_form.html.erb
<%= form_with(model: smart_expense, local: true, builder: InlineErrorsFormBuilder, class: 'form') do |form| %>
  <div class='form__field'>
    <%= form.label :expression %>
    <%= form.text_field :expression, id: :smart_expense_expression, class: 'input', required: true %>
    <%= form.inline_errors :expression %>
  </div>

  <div class='form__field form__field--currency'>
    <%= form.label :amount %>
    <span>
      <%= form.number_field :amount, min: 0, step: 'any', id: :smart_expense_amount, class: 'input' %>
      <%= current_user.currency %>
    </span>
    <%= form.inline_errors :amount %>
  </div>

  <div class='form__field'>
    <%= form.label :description %>
    <%= form.text_area :description, id: :smart_expense_description, class: 'h-fixed-textarea' %>
    <%= form.inline_errors :description %>
  </div>

  <div class='form__field'>
    <%= form.label :categories %>
    <%= form.collection_select :category_ids, current_user.categories, :id, :name, {},
      {
        multiple: true,
        id: :expense_categories,
        class: 'h-fixed-select'
      }
    %>
    <%= form.inline_errors :categories %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/smart_expenses/edit.html.erb
<h1>Editing Smart Expense</h1>

<%= render 'form', smart_expense: @smart_expense %>

<%= link_to 'Show', @smart_expense %> |
<%= link_to 'Back', smart_expenses_path %>

app/views/smart_expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Smart Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Expression</th>
      <th>Amount</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @smart_expenses.each do |smart_expense| %>
      <tr>
        <td><%= smart_expense.expression %></td>
        <td><%= number_to_currency(smart_expense.amount, unit: current_user.currency) %></td>
        <td><%= smart_expense.description %></td>
        <td><%= link_to 'Show', smart_expense %></td>
        <td><%= link_to 'Edit', edit_smart_expense_path(smart_expense) %></td>
        <td><%= link_to 'Destroy', smart_expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Smart Expense', new_smart_expense_path %>

app/views/smart_expenses/new.html.erb
<h1>New Smart Expense</h1>

<%= render 'form', smart_expense: @smart_expense %>

<%= link_to 'Back', smart_expenses_path %>

app/views/smart_expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expression:</strong>
  <%= @smart_expense.expression %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@smart_expense.amount, unit: current_user.currency) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @smart_expense.description %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @smart_expense.categories.pluck(:name).join(', ') %>
</p>

<%= link_to 'Edit', edit_smart_expense_path(@smart_expense) %> |
<%= link_to 'Back', smart_expenses_path %>